project:
  type: website

website:
  title: "LNSC Browser"
  page-navigation: false
  
  sidebar:
    style: docked
    search: true
    contents:
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: pubs.qmd
      - text: Atlases
        href: atlases.qmd
      - text: Investigators
        href: investigators.qmd
      
format:
  html:
    link-external-newwindow: true
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, dark.scss, theme.scss]
    mainfont: "Atkinson Hyperlegible"
    toc: true
    toc-depth: 1

editor: visual

