project:
  type: website

website:
  title: "LNSC Browser"
  navbar:
    search: true
    left:
      - projects.qmd
      - atlases.qmd
      - pubs.qmd
      - investigators.qmd
  search:
    location: navbar
    type: textbox

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

