---
title: Mechanisms of immune protection and pathology by lymph node stromal cells
page-layout: full
title-block-banner: true
---

The theme uniting our program is that lymph node stromal cells (LNSC)s are an
understudied and untapped source of immunomodulatory control.
LNSCs are comprised of diverse populations of fibroblasts and endothelial cells.
LNSCs coordinate lymphocyte entry into the lymph node (LN), facilitate
lymphocyte trafficking into distinct LN niches, regulate lymphocyte survival,
and promote LN expansion.
Our overall hypothesis is that viral and antigen acquisition by LNSCs shapes
immunity by programming pathogen and vaccine specific responses, and that LNSCs
can be manipulated by pathogens and vaccines to guide immune outcomes.

## Projects

* [Define protective and pathogenic roles of LNSCs during viral infection](projects.qmd#define-protective-and-pathogenic-roles-of-lnscs-during-viral-infection){.bold-link}  
Project 1 will define how viral targeting of distinct LNSCs regulates viral dissemination, LN organization and inflammation, and development of adaptive immunity  
[Thomas E Morrison, PhD](investigators.qmd#thomas-e-morrison-pdh){.link-box} [Publications](pubs.qmd#category=project-1){.link-box} [Atlases](atlases.qmd#category=project-1){.link-box}

* [Identify mechanisms of vaccine antigen localization and retention by LNSCs that drive and enhance cellular and humoral immunity](projects.qmd#identify-mechanisms-of-vaccine-antigen-localization-and-retention-by-lnscs-that-drive-and-enhance-cellular-and-humoral-immunity){.bold-link}  
Project 2 will define mechanisms of vaccine antigen acquisition and retention by different LNSCs  
[Beth A Jirón Tamburini, PhD](investigators.qmd#beth-a-jirón-tamburini-phd){.link-box} [Publications](pubs.qmd#category=project-2){.link-box} [Atlases](atlases.qmd#category=project-2){.link-box}

* [Investigate the role of immune complexes in antigen acquisition and retention by LNSCs to modulate cellular and humoral immunity](projects.qmd#investigate-the-role-of-immune-complexes-in-antigen-acquisition-and-retention-by-lnscs-to-modulate-cellular-and-humoral-immunity){.bold-link}  
Project 3 will use stabilized DNA conjugates to track antibody:antigen complexes to determine the spatial and cellular localization of immune complexes  
[Jenna Guthmiller, PhD](investigators.qmd#jenna-guthmiller-phd){.link-box} [Publications](pubs.qmd#category=project-3){.link-box} [Atlases](atlases.qmd#category=project-3){.link-box}

## Impact

Our multidisciplinary team nucleates a program for the study of LNSC biology
during infection and vaccination. Key scientific outcomes include:

1. New vaccine strategies and therapies to target LNSCs to combat pathogens
2. A mechanistic understanding of how viral targeting of LNSCs leads to
protection or pathology
3. Insights into how LNSCs regulate antigen-antibody acquisition through
complement and FcRs
4. Molecular approaches that overcome difficulties in evaluating LNSC
contributions to immunity and infection
5. Generation of new mouse models and human tissues systems to redefine LNSC
function in immunity
