---
title: Species-specific MARCO-alphavirus interactions dictate chikungunya virus viremia
categories: [project-1]
about:
  id: about
  template: jolla
  links:
  - text: Publication
    icon: file-earmark
    href: https://pubmed.ncbi.nlm.nih.gov/37083332/
---

[Frances Li](https://orcid.org/0000-0001-8798-8290), Kathryn Carpentier, David Hawman, Cormac Lucas, Stephanie Ander, Heinz Feldmann, Thomas Morrison

Arboviruses are public health threats that cause explosive outbreaks. Major determinants of arbovirus transmission, geographic spread, and pathogenesis are the magnitude and duration of viremia in vertebrate hosts. Previously, we determined that multiple alphaviruses are cleared efficiently from murine circulation by the scavenger receptor MARCO (Macrophage receptor with collagenous structure). Here, we define biochemical features on chikungunya (CHIKV), o'nyong 'nyong (ONNV), and Ross River (RRV) viruses required for MARCO-dependent clearance in vivo. In vitro, MARCO expression promotes binding and internalization of CHIKV, ONNV, and RRV via the scavenger receptor cysteine-rich (SRCR) domain. Furthermore, we observe species-specific effects of the MARCO SRCR domain on CHIKV internalization, where those from known amplification hosts fail to promote CHIKV internalization. Consistent with this observation, CHIKV is inefficiently cleared from the circulation of rhesus macaques in contrast with mice. These findings suggest a role for MARCO in determining whether a vertebrate serves as an amplification or dead-end host following CHIKV infection.
