---
title: Chikungunya virus infection disrupts lymph node lymphatic endothelial cell composition and function via MARCO

subtitle: '[Atlas](https://morrison-lnsc-browser.s3.amazonaws.com/index.html){.link-box-large}'
date: 'January 09, 2024'
categories: [Project-1, Project-2, Core-C, Core-D, 2024]
about:
  id: about
  template: jolla
  links:
  - text: Publication
    icon: file-earmark
    href: https://pubmed.ncbi.nlm.nih.gov/38194268/
  - text: GitHub
    icon: github
    href: https://github.com/rnabioco/morrison-lnsc
  - text: NCBI GEO
    href: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE243638
---

Cormac Lucas, [Ryan Sheridan](https://orcid.org/0000-0003-4012-3147), Glennys Reynoso, Bennett Davenport, Mary McCarthy, Aspen Martin, [Jay Hesselberth](https://scholar.google.com/citations?user=EnOmNEYAAAAJ), Heather Hickman, [Beth Tamburini](https://orcid.org/0000-0003-1991-231X), [Thomas Morrison](https://scholar.google.com/citations?user=ljkm0eMAAAAJ&hl=en&oi=ao)

Infection with chikungunya virus (CHIKV) causes disruption of draining lymph node (dLN) organization, including paracortical relocalization of B cells, loss of the B cell-T cell border, and lymphocyte depletion that is associated with infiltration of the LN with inflammatory myeloid cells. Here, we find that during the first 24 h of infection, CHIKV RNA accumulates in MARCO-expressing lymphatic endothelial cells (LECs) in both the floor and medullary LN sinuses. The accumulation of viral RNA in the LN was associated with a switch to an antiviral and inflammatory gene expression program across LN stromal cells, and this inflammatory response, including recruitment of myeloid cells to the LN, was accelerated by CHIKV-MARCO interactions. As CHIKV infection progressed, both floor and medullary LECs diminished in number, suggesting further functional impairment of the LN by infection. Consistent with this idea, we find that antigen acquisition by LECs, a key function of LN LECs during infection and immunization, was reduced during pathogenic CHIKV infection.
