---
title: Anaerobic respiration of host-derived methionine sulfoxide protects intracellular Salmonella from the phagocyte NADPH oxidase

subtitle: 'PMID 38307020'
date: 'January 24, 2024'
categories: [Project-1, Core-B, 2024]
about:
  id: about
  template: jolla
  links:
  - text: Pubmed
    icon: file-earmark
    href: https://pubmed.ncbi.nlm.nih.gov/38307020/
---

Ju-Sim Kim, Lin Liu, Sashi Kant, David Orlicky, Siva Uppalapati, Alyssa Margolis, Bennett Davenport, [Thomas Morrison](https://scholar.google.com/citations?user=ljkm0eMAAAAJ&hl=en&oi=ao), [Jennifer Matsuda](https://scholar.google.com/citations?user=xNd-F7YAAAAJ), Michael McClelland, Jessica Jones-Carson, Andres Vazquez-Torres

Intracellular Salmonella experiencing oxidative stress downregulates aerobic respiration. To maintain cellular energetics during periods of oxidative stress, intracellular Salmonella must utilize terminal electron acceptors of lower energetic value than molecular oxygen. We show here that intracellular Salmonella undergoes anaerobic respiration during adaptation to the respiratory burst of the phagocyte NADPH oxidase in macrophages and in mice. Reactive oxygen species generated by phagocytes oxidize methionine, generating methionine sulfoxide. Anaerobic Salmonella uses the molybdenum cofactor-containing DmsABC enzymatic complex to reduce methionine sulfoxide. The enzymatic activity of the methionine sulfoxide reductase DmsABC helps Salmonella maintain an alkaline cytoplasm that supports the synthesis of the antioxidant hydrogen sulfide via cysteine desulfuration while providing a source of methionine and fostering redox balancing by associated dehydrogenases. Our investigations demonstrate that nontyphoidal Salmonella responding to oxidative stress exploits the anaerobic metabolism associated with dmsABC gene products, a pathway that has accrued inactivating mutations in human-adapted typhoidal serovars.
